package crypto

// Cross-implementation conformance vectors (see docs/CRYPTO_FORMAT.md).
//
// This test is BOTH the reference generator and the Go verifier for
// app/backend/crypto/testvectors/vectors.json — the fixture every zcrypt
// client implementation (TS, Go, Rust) must pass so that a file encrypted on
// one client decrypts on all others.
//
//	Generate:  ZCRYPT_GEN_VECTORS=1 go test ./crypto/ -run TestCryptoVectors
//	Verify:    go test ./crypto/ -run TestCryptoVectors
//
// Vectors are decrypt/derive-direction (fixed IVs are embedded in stored
// ciphertexts) so implementations never need IV-injectable encrypt APIs; their
// encrypt sides are covered by round-trip tests in each language.

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/zcrypt/zcrypt-sidecar/compression"
)

const vectorsRelPath = "../../../backend/crypto/testvectors/vectors.json"

type pbkdf2Vector struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	SaltHex  string `json:"salt_hex,omitempty"`
	SaltText string `json:"salt_text,omitempty"` // UTF-8 text salt (name/dedup keys)
	KeyHex   string `json:"key_hex"`
}

type gcmVector struct {
	Name         string `json:"name"`
	KeyHex       string `json:"key_hex"`
	WireHex      string `json:"wire_hex"` // [12B IV || ct || 16B tag]
	PlaintextHex string `json:"plaintext_hex"`
}

type unwrapVector struct {
	Name       string `json:"name"`
	KekHex     string `json:"kek_hex"`
	WrappedHex string `json:"wrapped_hex"`
	CekHex     string `json:"cek_hex"`
}

type resolveVector struct {
	Name          string `json:"name"`
	Passphrase    string `json:"passphrase"`
	SaltHex       string `json:"salt_hex"`
	WrappedCekB64 string `json:"wrapped_cek_b64"`
	CekHex        string `json:"cek_hex"`
}

type sha256Vector struct {
	Name    string `json:"name"`
	DataHex string `json:"data_hex"`
	Hex     string `json:"sha256_hex"`
}

type hmacVector struct {
	Name    string `json:"name"`
	KeyHex  string `json:"key_hex"`
	DataHex string `json:"data_hex"`
	MacHex  string `json:"mac_hex"`
}

type nameVector struct {
	Name         string `json:"name"`
	Passphrase   string `json:"passphrase"`
	UserID       string `json:"user_id"`
	EncryptedB64 string `json:"encrypted_b64"`
	Plaintext    string `json:"plaintext"`
}

type zstdVector struct {
	Name          string `json:"name"`
	CompressedHex string `json:"compressed_hex"`
	PlaintextHex  string `json:"plaintext_hex"`
}

type vectorFile struct {
	Comment string          `json:"_comment"`
	Pbkdf2  []pbkdf2Vector  `json:"pbkdf2"`
	Gcm     []gcmVector     `json:"gcm_decrypt"`
	Unwrap  []unwrapVector  `json:"cek_unwrap"`
	Resolve []resolveVector `json:"resolve_file_key"`
	Sha256  []sha256Vector  `json:"sha256"`
	Hmac    []hmacVector    `json:"hmac_sha256"`
	Names   []nameVector    `json:"name_decrypt"`
	Zstd    []zstdVector    `json:"zstd_roundtrip"`
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex in vector: %v", err)
	}
	return b
}

// sealWithIV is a deterministic AES-GCM encrypt for GENERATION only — fixed IV,
// producing the standard wire format [IV || ct || tag]. Production code must
// keep using random IVs (EncryptChunk).
func sealWithIV(t *testing.T, key, iv, plaintext []byte) []byte {
	t.Helper()
	block, err := aes.NewCipher(key)
	if err != nil {
		t.Fatalf("aes: %v", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		t.Fatalf("gcm: %v", err)
	}
	out := make([]byte, 0, len(iv)+len(plaintext)+16)
	out = append(out, iv...)
	return gcm.Seal(out, iv, plaintext, nil)
}

// patterned returns n deterministic bytes (i*7+13 mod 256).
func patterned(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte((i*7 + 13) % 256)
	}
	return b
}

func generateVectors(t *testing.T) *vectorFile {
	t.Helper()
	v := &vectorFile{
		Comment: "GENERATED by app/desktop/sidecar/crypto/vectors_test.go (ZCRYPT_GEN_VECTORS=1). Normative spec: docs/CRYPTO_FORMAT.md. Do not hand-edit.",
	}

	// Fixed inputs. Salts/keys/IVs are arbitrary but stable constants.
	saltA := patterned(32)
	ivA := mustHex(t, "0102030405060708090a0b0c")
	ivB := mustHex(t, "f0e0d0c0b0a090807060504f")

	// --- PBKDF2 (600k, SHA-256, 32B) ---
	passASCII := "correct horse battery staple"
	passUnicode := "пароль-סיסמה-密码 🔐"
	keyASCII := DeriveKey(passASCII, saltA)
	keyUnicode := DeriveKey(passUnicode, saltA)
	nameSalt := "zcrypt-names-11111111-2222-3333-4444-555555555555"
	dedupSalt := "zcrypt-dedup-11111111-2222-3333-4444-555555555555"
	nameKey := DeriveKey(passASCII, []byte(nameSalt))
	dedupKey := DeriveKey(passASCII, []byte(dedupSalt))
	v.Pbkdf2 = []pbkdf2Vector{
		{Name: "ascii-passphrase", Password: passASCII, SaltHex: hex.EncodeToString(saltA), KeyHex: hex.EncodeToString(keyASCII)},
		{Name: "unicode-passphrase-utf8", Password: passUnicode, SaltHex: hex.EncodeToString(saltA), KeyHex: hex.EncodeToString(keyUnicode)},
		{Name: "name-key-text-salt", Password: passASCII, SaltText: nameSalt, KeyHex: hex.EncodeToString(nameKey)},
		{Name: "dedup-key-text-salt", Password: passASCII, SaltText: dedupSalt, KeyHex: hex.EncodeToString(dedupKey)},
	}

	// --- GCM decrypt (wire → plaintext) ---
	cek := patterned(32)
	empty := []byte{}
	oneByte := []byte{0x42}
	blockSized := patterned(16)
	chunkLike := patterned(4096)
	v.Gcm = []gcmVector{
		{Name: "empty-plaintext", KeyHex: hex.EncodeToString(cek), WireHex: hex.EncodeToString(sealWithIV(t, cek, ivA, empty)), PlaintextHex: ""},
		{Name: "one-byte", KeyHex: hex.EncodeToString(cek), WireHex: hex.EncodeToString(sealWithIV(t, cek, ivA, oneByte)), PlaintextHex: hex.EncodeToString(oneByte)},
		{Name: "block-sized-16", KeyHex: hex.EncodeToString(cek), WireHex: hex.EncodeToString(sealWithIV(t, cek, ivB, blockSized)), PlaintextHex: hex.EncodeToString(blockSized)},
		{Name: "chunk-4096", KeyHex: hex.EncodeToString(cek), WireHex: hex.EncodeToString(sealWithIV(t, cek, ivB, chunkLike)), PlaintextHex: hex.EncodeToString(chunkLike)},
	}

	// --- CEK unwrap ---
	wrapped := sealWithIV(t, keyASCII, ivA, cek)
	v.Unwrap = []unwrapVector{
		{Name: "wrap-under-passphrase-kek", KekHex: hex.EncodeToString(keyASCII), WrappedHex: hex.EncodeToString(wrapped), CekHex: hex.EncodeToString(cek)},
	}

	// --- End-to-end: passphrase → KEK → unwrap → CEK ---
	v.Resolve = []resolveVector{
		{Name: "envelope-resolution", Passphrase: passASCII, SaltHex: hex.EncodeToString(saltA), WrappedCekB64: base64.StdEncoding.EncodeToString(wrapped), CekHex: hex.EncodeToString(cek)},
	}

	// --- SHA-256 ---
	abc := []byte("abc")
	v.Sha256 = []sha256Vector{
		{Name: "empty", DataHex: "", Hex: SHA256Hex(nil)},
		{Name: "abc", DataHex: hex.EncodeToString(abc), Hex: SHA256Hex(abc)},
		{Name: "patterned-1024", DataHex: hex.EncodeToString(patterned(1024)), Hex: SHA256Hex(patterned(1024))},
	}

	// --- HMAC-SHA256 (hmac_v1 content MAC) under the dedup key ---
	mac := hmac.New(sha256.New, dedupKey)
	mac.Write(chunkLike)
	v.Hmac = []hmacVector{
		{Name: "hmac_v1-under-dedup-key", KeyHex: hex.EncodeToString(dedupKey), DataHex: hex.EncodeToString(chunkLike), MacHex: hex.EncodeToString(mac.Sum(nil))},
	}

	// --- Name decryption (per-user name key) ---
	plainName := "Quarterly Report — 密码 🔐.pdf"
	encName := sealWithIV(t, nameKey, ivB, []byte(plainName))
	v.Names = []nameVector{
		{Name: "unicode-filename", Passphrase: passASCII, UserID: "11111111-2222-3333-4444-555555555555", EncryptedB64: base64.StdEncoding.EncodeToString(encName), Plaintext: plainName},
	}

	// --- zstd round-trip (format compatibility, not byte-parity) ---
	compressible := bytes.Repeat([]byte("zcrypt zero-knowledge storage "), 200)
	comp, ok := compression.Compress(compressible, 2)
	if !ok {
		t.Fatal("expected the repeated sample to compress")
	}
	v.Zstd = []zstdVector{
		{Name: "repeated-text-level2", CompressedHex: hex.EncodeToString(comp), PlaintextHex: hex.EncodeToString(compressible)},
	}

	return v
}

func verifyVectors(t *testing.T, v *vectorFile) {
	t.Helper()

	for _, c := range v.Pbkdf2 {
		salt := []byte(c.SaltText)
		if c.SaltHex != "" {
			salt = mustHex(t, c.SaltHex)
		}
		got := DeriveKey(c.Password, salt)
		if hex.EncodeToString(got) != c.KeyHex {
			t.Errorf("pbkdf2 %s: key mismatch", c.Name)
		}
	}

	for _, c := range v.Gcm {
		got, err := DecryptChunk(mustHex(t, c.KeyHex), mustHex(t, c.WireHex))
		if err != nil {
			t.Errorf("gcm %s: %v", c.Name, err)
			continue
		}
		if hex.EncodeToString(got) != c.PlaintextHex {
			t.Errorf("gcm %s: plaintext mismatch", c.Name)
		}
	}

	for _, c := range v.Unwrap {
		got, err := UnwrapCEK(mustHex(t, c.KekHex), mustHex(t, c.WrappedHex))
		if err != nil {
			t.Errorf("unwrap %s: %v", c.Name, err)
			continue
		}
		if hex.EncodeToString(got) != c.CekHex {
			t.Errorf("unwrap %s: cek mismatch", c.Name)
		}
	}

	for _, c := range v.Resolve {
		kek := DeriveKey(c.Passphrase, mustHex(t, c.SaltHex))
		wrapped, err := base64.StdEncoding.DecodeString(c.WrappedCekB64)
		if err != nil {
			t.Fatalf("resolve %s: bad b64: %v", c.Name, err)
		}
		cek, err := UnwrapCEK(kek, wrapped)
		if err != nil {
			t.Errorf("resolve %s: %v", c.Name, err)
			continue
		}
		if hex.EncodeToString(cek) != c.CekHex {
			t.Errorf("resolve %s: cek mismatch", c.Name)
		}
	}

	for _, c := range v.Sha256 {
		if got := SHA256Hex(mustHex(t, c.DataHex)); got != c.Hex {
			t.Errorf("sha256 %s: mismatch", c.Name)
		}
	}

	for _, c := range v.Hmac {
		mac := hmac.New(sha256.New, mustHex(t, c.KeyHex))
		mac.Write(mustHex(t, c.DataHex))
		if hex.EncodeToString(mac.Sum(nil)) != c.MacHex {
			t.Errorf("hmac %s: mismatch", c.Name)
		}
	}

	for _, c := range v.Names {
		nameKey := DeriveKey(c.Passphrase, []byte("zcrypt-names-"+c.UserID))
		enc, err := base64.StdEncoding.DecodeString(c.EncryptedB64)
		if err != nil {
			t.Fatalf("name %s: bad b64: %v", c.Name, err)
		}
		got, err := DecryptChunk(nameKey, enc)
		if err != nil {
			t.Errorf("name %s: %v", c.Name, err)
			continue
		}
		if string(got) != c.Plaintext {
			t.Errorf("name %s: plaintext mismatch: %q", c.Name, string(got))
		}
	}

	for _, c := range v.Zstd {
		got, err := compression.Decompress(mustHex(t, c.CompressedHex))
		if err != nil {
			t.Errorf("zstd %s: %v", c.Name, err)
			continue
		}
		if hex.EncodeToString(got) != c.PlaintextHex {
			t.Errorf("zstd %s: round-trip mismatch", c.Name)
		}
	}
}

func TestCryptoVectors(t *testing.T) {
	if os.Getenv("ZCRYPT_GEN_VECTORS") == "1" {
		v := generateVectors(t)
		verifyVectors(t, v) // never write vectors this implementation can't read back
		data, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		if err := os.MkdirAll(filepath.Dir(vectorsRelPath), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(vectorsRelPath, append(data, '\n'), 0o644); err != nil {
			t.Fatalf("write vectors: %v", err)
		}
		t.Logf("wrote %s", vectorsRelPath)
		return
	}

	data, err := os.ReadFile(vectorsRelPath)
	if err != nil {
		t.Fatalf("vectors file missing (%v) — generate with ZCRYPT_GEN_VECTORS=1", err)
	}
	var v vectorFile
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Pbkdf2) == 0 || len(v.Gcm) == 0 {
		t.Fatal("vectors file looks empty")
	}
	verifyVectors(t, &v)
}

// TestEncryptRoundTrip covers the random-IV encrypt side (vectors cover decrypt).
func TestEncryptRoundTrip(t *testing.T) {
	key := patterned(32)
	plain := patterned(1000)
	wire, err := EncryptChunk(key, plain)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if len(wire) != len(plain)+28 {
		t.Fatalf("wire size %d, want %d (+12 IV +16 tag)", len(wire), len(plain)+28)
	}
	got, err := DecryptChunk(key, wire)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if !bytes.Equal(got, plain) {
		t.Fatal("round-trip mismatch")
	}
	// Tampering must fail auth.
	wire[len(wire)-1] ^= 0xff
	if _, err := DecryptChunk(key, wire); err == nil {
		t.Fatal("tampered ciphertext decrypted successfully")
	}
}
